@baseUrl = http://localhost:{{$dotenv PORT}}

### Resitration for a new User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "first_name": "Jane",
    "last_name": "Doe",
    "pseudo": "Jj",
    "email": "jjdoe@gmail.com",
    "password":"@Jjdoe123"
}

### Loggin for a User
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "jjdoe@gmail.com",
    "password":"@Jjdoe1234"
}

### GET info about me
GET {{baseUrl}}/auth/me
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "email": "jjdoe@gmail.com",
    "password":"@Jjdoe123"
}


### Updating infos User
PATCH {{baseUrl}}/auth/me
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "first_name": "John",
    "last_name": "Doe",
    "password":"@Jjdoe1234"
}